// miniaudioとstb_vorbisの実装を含める翻訳単位
// (stb_vorbisをminiaudioより先にヘッダのみ取り込むことでOgg Vorbisデコードが有効になる)
// (EMSCRIPTEN_KEEPALIVEの関数名がC++だとマングリングされてJS側から参照できなくなるためCとしてコンパイルする)

// libSiv3D.a内のstb_vorbisとのシンボル衝突を避けるためリネーム
#define stb_vorbis_open_pushdata ksmaudio_stb_vorbis_open_pushdata
#define stb_vorbis_decode_frame_pushdata ksmaudio_stb_vorbis_decode_frame_pushdata
#define stb_vorbis_flush_pushdata ksmaudio_stb_vorbis_flush_pushdata
#define stb_vorbis_decode_filename ksmaudio_stb_vorbis_decode_filename
#define stb_vorbis_decode_memory ksmaudio_stb_vorbis_decode_memory
#define stb_vorbis_open_memory ksmaudio_stb_vorbis_open_memory
#define stb_vorbis_open_filename ksmaudio_stb_vorbis_open_filename
#define stb_vorbis_open_file ksmaudio_stb_vorbis_open_file
#define stb_vorbis_open_file_section ksmaudio_stb_vorbis_open_file_section
#define stb_vorbis_close ksmaudio_stb_vorbis_close
#define stb_vorbis_get_sample_offset ksmaudio_stb_vorbis_get_sample_offset
#define stb_vorbis_get_playback_sample_offset ksmaudio_stb_vorbis_get_playback_sample_offset
#define stb_vorbis_get_file_offset ksmaudio_stb_vorbis_get_file_offset
#define stb_vorbis_get_info ksmaudio_stb_vorbis_get_info
#define stb_vorbis_get_comment ksmaudio_stb_vorbis_get_comment
#define stb_vorbis_get_error ksmaudio_stb_vorbis_get_error
#define stb_vorbis_stream_length_in_samples ksmaudio_stb_vorbis_stream_length_in_samples
#define stb_vorbis_stream_length_in_seconds ksmaudio_stb_vorbis_stream_length_in_seconds
#define stb_vorbis_get_frame_float ksmaudio_stb_vorbis_get_frame_float
#define stb_vorbis_get_frame_short ksmaudio_stb_vorbis_get_frame_short
#define stb_vorbis_get_frame_short_interleaved ksmaudio_stb_vorbis_get_frame_short_interleaved
#define stb_vorbis_get_samples_float ksmaudio_stb_vorbis_get_samples_float
#define stb_vorbis_get_samples_float_interleaved ksmaudio_stb_vorbis_get_samples_float_interleaved
#define stb_vorbis_get_samples_short ksmaudio_stb_vorbis_get_samples_short
#define stb_vorbis_get_samples_short_interleaved ksmaudio_stb_vorbis_get_samples_short_interleaved
#define stb_vorbis_seek ksmaudio_stb_vorbis_seek
#define stb_vorbis_seek_frame ksmaudio_stb_vorbis_seek_frame
#define stb_vorbis_seek_start ksmaudio_stb_vorbis_seek_start

#define STB_VORBIS_HEADER_ONLY
#include "stb_vorbis.c"

#define MINIAUDIO_IMPLEMENTATION
#define MA_NO_ENCODING
#define MA_NO_GENERATION
#include "miniaudio.h"

// stb_vorbisの実装はminiaudioの実装より後に含める必要がある
#undef STB_VORBIS_HEADER_ONLY
#include "stb_vorbis.c"
